export enum AnnouncementType {
  ORDER = "ORDER",
  AUCTION = "AUCTION",
  EXCHANGE_NEW_REQUEST = "EXCHANGE_NEW_REQUEST",
  EXCHANGE_APPROVED = "EXCHANGE_APPROVED",
  EXCHANGE_REJECTED = "EXCHANGE_REJECTED",
  EXCHANGE_NEW_DEAL = "EXCHANGE_NEW_DEAL",
  EXCHANGE_DELIVERY = "EXCHANGE_DELIVERY",
  EXCHANGE_SUCCESSFUL = "EXCHANGE_SUCCESSFUL",
  EXCHANGE_FAILED = "EXCHANGE_FAILED",
}
